version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependency"
    # Always increase the version requirement to match the new version.
    versioning-strategy: increase
